import type { ParseSourceInput } from './types';

export const POLITICS_SOURCE_CATALOG: Omit<ParseSourceInput, 'id'>[] = [
  {
    name: 'BBC News Politics',
    baseUrl: 'https://feeds.bbci.co.uk/news/politics/rss.xml',
    language: 'en',
    country: 'GB',
    fetchMode: 'RSS',
    accessMode: 'FULL_OPEN',
    politicsOnly: true,
  },
  {
    name: 'Associated Press Politics',
    baseUrl: 'https://apnews.com/politics',
    language: 'en',
    country: 'US',
    fetchMode: 'SECTION_HTML',
    accessMode: 'FULL_OPEN',
    politicsOnly: true,
  },
  {
    name: 'PBS NewsHour Politics',
    baseUrl: 'https://www.pbs.org/newshour/politics',
    language: 'en',
    country: 'US',
    fetchMode: 'SECTION_HTML',
    accessMode: 'FULL_OPEN',
    politicsOnly: true,
  },
  {
    name: 'ProPublica Politics',
    baseUrl: 'https://www.propublica.org/topics/politics',
    language: 'en',
    country: 'US',
    fetchMode: 'SECTION_HTML',
    accessMode: 'FULL_OPEN',
    politicsOnly: true,
  },
  {
    name: 'Al Jazeera News',
    baseUrl: 'https://www.aljazeera.com/news/',
    language: 'en',
    country: 'QA',
    fetchMode: 'SECTION_HTML',
    accessMode: 'FULL_OPEN',
    politicsOnly: true,
  },
  {
    name: 'The New York Times Politics',
    baseUrl: 'https://www.nytimes.com/section/politics',
    language: 'en',
    country: 'US',
    fetchMode: 'SECTION_HTML',
    accessMode: 'METADATA_ONLY',
    politicsOnly: true,
  },
  {
    name: 'Reuters World',
    baseUrl: 'https://www.reuters.com/world/',
    language: 'en',
    country: 'GB',
    fetchMode: 'SECTION_HTML',
    accessMode: 'METADATA_ONLY',
    politicsOnly: true,
  },
  {
    name: 'Bloomberg Politics',
    baseUrl: 'https://www.bloomberg.com/politics',
    language: 'en',
    country: 'US',
    fetchMode: 'SECTION_HTML',
    accessMode: 'METADATA_ONLY',
    politicsOnly: true,
  },
  {
    name: 'WSJ Politics',
    baseUrl: 'https://www.wsj.com/politics',
    language: 'en',
    country: 'US',
    fetchMode: 'SECTION_HTML',
    accessMode: 'METADATA_ONLY',
    politicsOnly: true,
  },
  {
    name: 'Financial Times World',
    baseUrl: 'https://www.ft.com/world',
    language: 'en',
    country: 'GB',
    fetchMode: 'SECTION_HTML',
    accessMode: 'METADATA_ONLY',
    politicsOnly: true,
  },
];